### ISSUE TITLE
Type or Namespace name DotNetOpenAuth could not be found.

### ISSUE THREAD

**Issue by jeffolmstead** [Jetski5822/NGM.OpenAuthentication#1]
Hello, trying out another of your great modules. I have used source control to pull down your Open Authentication module and then used Orchard packager to create the package for deployment to my site (it is an Azure website if that matters). No matter what I do, it continually throws a "The type or namespace name 'DotNetOpenAuth' could not be found" when I visit the logon page. Just wondering if you have experienced this? 

I have even tried forgetting the packaging manager and just dragging the raw project over to the live server and still same message. I also tried adding a reference right in the module Web.Config to DotNetOpenAuth.AspNet but still nothing. Look forward to any thoughts you might have.

UPDATE: I attempted to use the module directly from the Orchard Gallery and had the same thing. It is really very strange as I can get it to work on localhost. Any thoughts are appreciated.

**Comment by Jetski5822** [comment]
Oddness. But, certain packages have become deprecated, so will need to pull the code in to keep up to date. Thanks for investigating.

**Comment by bhavikprulogics** [comment]
I just installed the module in Orchard 1.8 version. It gave me the same error.
I commented out "@using DotNetOpenAuth.AspNet" from NGM.OpenAuthentication\Views\OpenAuthLogOn.cshtml and it worked

Not sure if this issue is resolved for you already or not.
Hope it helps to you or others.

**Comment by santo2** [comment]
Same issue. Is this module not maintained anymore?

**Comment by Jetski5822** [comment]
The module is maintained and is run on the asp blogs. I am tied up till
Friday, so will take a look this weekend.

Same issue. Is this module not maintained anymore?

**Comment by Jetski5822** [comment]
Have you tried the fix mentioned in this thread?

**Comment by Jetski5822** [comment]
So this "@using DotNetOpenAuth.AspNet" is not actually needed in that view. I have taken it out.
