### ISSUE TITLE
Microsoft.Bcl.Build.Targets not found

### ISSUE THREAD

**Issue by davegardner** [Jetski5822/NGM.OpenAuthentication#10]
On trying to add the project to Orchard 1.9 in VS I get the following error:

The imported project ...NMG.OpenAuthentication\packages\Microsoft.Bcl.Build.1.0.8\tools\Microsoft.Bcl.Build.Targets was not found. Confirm that the path exists and that the <import> declaration is correct and that the file exists on disk.

I used NUGET to install Microsoft.Bcl.Build but it made no difference.

Not sure where to go from here. Why not put dependencies in a project lib folder?

**Comment by davegardner** [comment]
OK, I did not realize this project is quite old. I removed the offending import statement from the project file so the project would open in VS and updated it to 4.5.1. It seems IUserEventHandler has been extended since this project was developed so for now I just implemented dummy methods for the two that were missing. It now compiles, which is all I need for the time being.

**Comment by Jetski5822** [comment]
Hey, I have been working on other projects recently, but will jump back to this soon.

The idea is to move to OWIN. N
